langchain4j:
  open-ai:
    chat-model:
      # api-key: demo
      model-name: gpt-3.5-turbo
      temperature: 0.0
      timeout: PT60S
      log-requests: false
      log-responses: false

logging.level.dev.langchain4j: DEBUG
